# Generated by Django 4.0.1 on 2022-05-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('0', 'less than 6 employees'), ('1', 'between 6 and 49 employees'), ('2', 'between 50 and 199 employees'), ('3', 'more than 200 employees')], max_length=100)),
                ('infos', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(max_length=100)),
                ('contract_type', models.CharField(choices=[('0', 'permanent contract'), ('1', 'fixed-term contract')], max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.company')),
            ],
        ),
    ]
