# Generated by Django 4.0.1 on 2022-05-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobportal.companyaddress'),
            preserve_default=False,
        ),
    ]
